Return available meeting times for mandatory + optional members
swalsh15/step-portfolio pull request #28
Opened 2020-06-12 18:21 UTC by swalsh15

Algorithm to find available meeting times for list of mandatory and optional members given length of the meeting and other meetings scheduled for that day. Pass 21 tests given with file and 5 tests I wrote to verify optional members are added correctly. This is from the week 5 walkthrough.

2020-06-15 17:03 UTC, augerm requested changes

2020-06-15 17:03 UTC, augerm commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
>    public Collection<TimeRange> query(Collection<Event> events, MeetingRequest request) {
Can we break this up into a few smaller functions for readability?

2020-06-15 17:40 UTC, Danish21 approved these changes
Nice job on this. I like the clarity of your tests!

2020-06-17 14:45 UTC, augerm approved these changes
Thanks for the changes!

2020-06-17 14:45 UTC, augerm commented on walkthroughs/week-5-tdd/project/src/main/java/com/google/sps/FindMeetingQuery.java
> +    ArrayList<TimeRange> availableTimes = findAvalibaleTimesMandatoryMembers(unavailableTimes, request);
`findAvalibaleTimesMandatoryMembers` --> `findAvailableTImesMandatoryMembers` typo in available

2020-06-17 18:46 UTC, merged